#! /usr/bin/env python
# -*- coding: utf-8 -*-
''' Рустам, мне как первому попался файд с уодировкой UTF-8 with BOM
            поэтому приходится работать с codecs '''
import codecs
stream_source = codecs.open('text.txt', 'r', 'utf-8')
text_for_save = []
# Забираем кодированный поток в List
words = stream_source.readline().split(' ')
stream_source.close()
# Исправляем на заглавные
for word in words:
    if (len(word) > 6 and word[-1] != '.' and word[-1] != ','):
        word = word.capitalize()
    text_for_save.append(word)

# Переоткрываем и записываем в тот же файл
exiting_file = open('text.txt', 'w')
for other_words in text_for_save:
    exiting_file.write('%s'' ' % other_words)
exiting_file.close()
